name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip
        run: zip -r PretixPlugin.zip PretixPlugin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: PretixPlugin.zip